export const siteTextDefinitions = [
  { key: "public.nav.team", group: "Публічна сторінка · меню", label: "Пункт «Команда»", value: "Команда" },
  { key: "public.nav.ctf", group: "Публічна сторінка · меню", label: "Пункт «CTF»", value: "CTF" },
  { key: "public.nav.writeups", group: "Публічна сторінка · меню", label: "Пункт «Writeups»", value: "Writeups" },
  { key: "public.nav.workspace", group: "Публічна сторінка · меню", label: "Кнопка робочого простору", value: "Team workspace" },
  { key: "public.hero.eyebrow", group: "Публічна сторінка · головний екран", label: "Надзаголовок", value: "UKRAINIAN CTF TEAM · EST. 2026" },
  { key: "public.hero.title1", group: "Публічна сторінка · головний екран", label: "Заголовок · рядок 1", value: "We find the flag." },
  { key: "public.hero.title2", group: "Публічна сторінка · головний екран", label: "Заголовок · рядок 2", value: "Then explain why." },
  { key: "public.hero.lead", group: "Публічна сторінка · головний екран", label: "Опис", value: "Ambr0s1a! — команда з кібербезпеки, що розв’язує задачі, ділиться знаннями та росте від одного CTF до наступного.", multiline: true },
  { key: "public.hero.writeups", group: "Публічна сторінка · головний екран", label: "Кнопка writeups", value: "Читати writeups" },
  { key: "public.hero.results", group: "Публічна сторінка · головний екран", label: "Посилання результатів", value: "Наші результати" },
  { key: "public.hero.next", group: "Публічна сторінка · головний екран", label: "Підпис наступної події", value: "NEXT OPERATION" },
  { key: "public.hero.nextName", group: "Публічна сторінка · головний екран", label: "Назва наступної події", value: "DEADFACE CTF" },
  { key: "public.hero.nextDate", group: "Публічна сторінка · головний екран", label: "Дата наступної події", value: "16 AUG · 15:00 EEST" },
  { key: "public.ticker.one", group: "Публічна сторінка · принципи", label: "Принцип 1", value: "RECON 15–20 MIN" },
  { key: "public.ticker.two", group: "Публічна сторінка · принципи", label: "Принцип 2", value: "1 OWNER + 1 HELPER" },
  { key: "public.ticker.three", group: "Публічна сторінка · принципи", label: "Принцип 3", value: "30 / 60 / 90 ESCALATION" },
  { key: "public.ticker.four", group: "Публічна сторінка · принципи", label: "Принцип 4", value: "STRUCTURED HANDOFF" },
  { key: "public.about.label", group: "Публічна сторінка · команда", label: "Номер розділу", value: "01 / THE TEAM" },
  { key: "public.about.title1", group: "Публічна сторінка · команда", label: "Заголовок · рядок 1", value: "Structured curiosity." },
  { key: "public.about.title2", group: "Публічна сторінка · команда", label: "Заголовок · рядок 2", value: "Collective momentum." },
  { key: "public.about.text", group: "Публічна сторінка · команда", label: "Опис команди", value: "Кожен учасник має Primary і Secondary напрям. На змаганні працюємо швидко, але не хаотично: фіксуємо прогрес, просимо допомогу й передаємо контекст без втрат.", multiline: true },
  { key: "public.about.members", group: "Публічна сторінка · команда", label: "Кількість учасників", value: "10–12" },
  { key: "public.about.membersLabel", group: "Публічна сторінка · команда", label: "Підпис учасників", value: "members" },
  { key: "public.about.disciplines", group: "Публічна сторінка · команда", label: "Кількість дисциплін", value: "6+" },
  { key: "public.about.disciplinesLabel", group: "Публічна сторінка · команда", label: "Підпис дисциплін", value: "disciplines" },
  { key: "public.about.curiosity", group: "Публічна сторінка · команда", label: "Показник допитливості", value: "∞" },
  { key: "public.about.curiosityLabel", group: "Публічна сторінка · команда", label: "Підпис допитливості", value: "curiosity" },
  { key: "public.results.label", group: "Публічна сторінка · результати", label: "Номер розділу", value: "02 / COMPETITIONS" },
  { key: "public.results.title", group: "Публічна сторінка · результати", label: "Заголовок", value: "Recent operations" },
  { key: "public.results.archive", group: "Публічна сторінка · результати", label: "Посилання архіву", value: "CTFTIME ARCHIVE ↗" },
  { key: "public.results.event", group: "Публічна сторінка · результати", label: "Колонка EVENT", value: "EVENT" },
  { key: "public.results.place", group: "Публічна сторінка · результати", label: "Колонка PLACE", value: "PLACE" },
  { key: "public.results.points", group: "Публічна сторінка · результати", label: "Колонка POINTS", value: "POINTS" },
  { key: "public.results.status", group: "Публічна сторінка · результати", label: "Колонка STATUS", value: "STATUS" },
  { key: "public.results.complete", group: "Публічна сторінка · результати", label: "Статус завершення", value: "● COMPLETE" },
  { key: "public.writeups.label", group: "Публічна сторінка · writeups", label: "Номер розділу", value: "03 / KNOWLEDGE BASE" },
  { key: "public.writeups.title", group: "Публічна сторінка · writeups", label: "Заголовок", value: "Latest writeups" },
  { key: "public.writeups.all", group: "Публічна сторінка · writeups", label: "Посилання на всі матеріали", value: "Усі матеріали →" },
  { key: "public.writeups.read", group: "Публічна сторінка · writeups", label: "Текст картки writeup", value: "READ THE WRITEUP ↗" },
  { key: "public.footer.tagline", group: "Публічна сторінка · підвал", label: "Гасло", value: "Learn. Break. Document. Repeat." },
  { key: "public.footer.workspace", group: "Публічна сторінка · підвал", label: "Посилання workspace", value: "Member workspace →" },
  { key: "workspace.title", group: "Робочий простір", label: "Заголовок workspace", value: "Team workspace" },
  { key: "workspace.nav.overview", group: "Робочий простір · меню", label: "Огляд", value: "Огляд" },
  { key: "workspace.nav.ctfs", group: "Робочий простір · меню", label: "CTF середовища", value: "CTF середовища" },
  { key: "workspace.nav.ctftime", group: "Робочий простір · меню", label: "CTFtime", value: "CTFtime" },
  { key: "workspace.nav.upcoming", group: "Робочий простір · меню", label: "Майбутні CTF", value: "Майбутні CTF" },
  { key: "workspace.nav.tasks", group: "Робочий простір · меню", label: "Активні таски", value: "Активні таски" },
  { key: "workspace.nav.members", group: "Робочий простір · меню", label: "Учасники", value: "Учасники" },
  { key: "workspace.nav.history", group: "Робочий простір · меню", label: "Виконані", value: "Виконані" },
  { key: "workspace.nav.archive", group: "Робочий простір · меню", label: "Архів CTF", value: "Архів CTF" },
  { key: "workspace.nav.notifications", group: "Робочий простір · меню", label: "Сповіщення", value: "Сповіщення" },
  { key: "workspace.nav.writeups", group: "Робочий простір · меню", label: "Writeups", value: "Writeups" },
  { key: "workspace.nav.content", group: "Робочий простір · меню", label: "Редактор текстів", value: "Тексти сайту" },
] as const;

export type SiteTextKey = typeof siteTextDefinitions[number]["key"];

export const siteTextDefaults = Object.fromEntries(siteTextDefinitions.map(item => [item.key, item.value])) as Record<SiteTextKey, string>;
